apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.app }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.service.adminPort }}
    name: {{ .Values.service.adminName }}
  - port: {{ .Values.service.clusterPort }}
    name: {{ .Values.service.clusterName }}
  - port: {{ .Values.service.postgresPort }}
    name: {{ .Values.service.postgresName }}
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app }}