apiVersion: v1
description: A Helm chart for Orion Context Broker
name: orion
version: 0.1.6
sources:
- https://github.com/telefonicaid/fiware-orion
maintainers:
- name: taliaga
  email: tomas.aliaga@martel-innovate.com
