apiVersion: v1
description: 'CrateDB chart'
name: crate
version: 0.1.14
icon: https://crate.io/wp-content/themes/webflow/images/logo-crate.png
sources:
- https://github.com/crate/crate
- https://github.com/crate/docker-crate
maintainers:
- name: undefinedhashtag
  email: d.sarah710@yahoo.com
