apiVersion: v1
description: A Helm chart for QuantumLeap
name: quantumleap
version: 0.1.19
sources:
- https://github.com/smartsdk/ngsi-timeseries-api
maintainers:
- name: taliaga
  email: tomas.aliaga@martel-innovate.com
